### ISSUE TITLE
Wifi connection restore

### ISSUE THREAD

**Issue by devmirek** [bonitoo-io/weather-station#18]
Device should periodically try to restore current WiFi connection when it is in AP mode to recover form WiFi connection drops.

**Comment by vlastahajek** [comment]
This is how it works from the beginning.
If there is a WiFi config and WiFi is not connected and the last error is not "authorization fail", a reconnection attempt is made each 30s, even AP is running.
The issue can be the device is simply not able to connect to WiFi, from an unknown reason.

**Comment by vlastahajek** [comment]
As tested at home, where the device was not able to connect to WiFi, after several hours I found the device was connected. This confirms the periodic reconnection works.
