### ISSUE TITLE
Main should be named master

### ISSUE THREAD

**Issue by ivankudibal** [bonitoo-io/weather-station#3]
The default branch is called main. It causes confusion.

Stanard is to call it `master`.

Therefore the master should be created and set as default

**Comment by vlastahajek** [comment]
This is because of the default branch name in the GitHub organization setting: [New GitHub Repositories Default to Main Branch](https://www.infoq.com/news/2020/10/github-main-branch/#:~:text=As%20of%20today%2C%20all%20newly,'%20instead%20of%20'master').

**Comment by devmirek** [comment]
Closed
