### ISSUE TITLE
Unit should be written to influxdb, too 

### ISSUE THREAD

**Issue by ivankudibal** [bonitoo-io/weather-station#6]
A unit in general should be written to Influxdb, too.

Temperature is configurable, degrees of Fahrenheit or Celsius. The data written to influxdb contain just a number.

It would be useful to know the unit in order to

1. use temperature  numbers from two stations in one chart
2. historical data in one device can be stored in two different units (uc: device reconfiguration)

**Comment by devmirek** [comment]
Added TemperatureUnit tag to specify unit, it is always C
